services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/forum
    depends_on:
      - database

  database:
    image: "nouchka/sqlite3"
    volumes:
      - ./database.db:/root/db.sqlite
